AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  S3BucketName:
    Type: String
    Description: Name for the DFO S3 bucket.
    Default: gmaist-dfo-s3subfolder434

  S3CodeKey:
    Type: String

  Environment:
    Type: String
    Description: What environment is being deployed
    Default: sbx
    AllowedValues:
      - sbx
      - dev
      - test
      - prod


Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        [
          { "Key": "PrimaryOwner", "Value": "PFE-RAPID-IAS-DEVELOPER-SSO/DARSHAN.ARAVIND@pfizer.com" },
          { "Key": "SecondaryOwner", "Value": "Eman" },
          { "Key": "Enviroment", "Value": "sbx"},
          { "Key": "CostCenterID" , "Value": "2331084"},
          { "Key": "Name","Value": "sbx-GMAIST" }
        ]
      BucketName: !Sub '${Environment}-${S3BucketName}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CustomLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Tags:
        [
          { "Key": "PrimaryOwner", "Value": "PFE-RAPID-IAS-DEVELOPER-SSO/DARSHAN.ARAVIND@pfizer.com" },
          { "Key": "SecondaryOwner", "Value": "Eman" },
          { "Key": "Enviroment", "Value": "sbx"},
          { "Key": "CostCenterID" , "Value": "2331084"},
          { "Key": "Name","Value": "sbx-GMAIST" }
        ]
      FunctionName: !Sub '${Environment}-${S3BucketName}'
      Handler: lambda_function.lambda_handler
      Role: "arn:aws:iam::433187729648:role/LambdaS3FullAccess"
      Runtime: python3.9
      Timeout: 300
      Code:
        S3Bucket: codebucket234
        S3Key: !Ref S3CodeKey

  CustomResource:
    Type: Custom::CustomResource
    Properties:
      Tags:
        [
          { "Key": "PrimaryOwner", "Value": "PFE-RAPID-IAS-DEVELOPER-SSO/DARSHAN.ARAVIND@pfizer.com" },
          { "Key": "SecondaryOwner", "Value": "Eman" },
          { "Key": "Enviroment", "Value": "sbx"},
          { "Key": "CostCenterID" , "Value": "2331084"},
          { "Key": "Name","Value": "sbx-GMAIST" }
        ]
      ServiceToken: !GetAtt CustomLambdaFunction.Arn