AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  S3BucketName:
    Type: String
    Description: Name for the S3 bucket.
    Default: productbucket3234

  Environment:
    Type: String
    Description: What environment is being deployed
    Default: dev
    AllowedValues:
      - sbx
      - dev
      - test
      - prod

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref S3BucketName
